Multiple Linear Regression

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df=pd.read_csv('blood.csv')
df

V1  V2     V3  V4  Class
0     2  50  12500  98      2
1     0  13   3250  28      2
2     1  16   4000  35      2
3     2  20   5000  45      2
4     1  24   6000  77      1
..   ..  ..    ...  ..    ...
743  23   2    500  38      1
744  21   2    500  52      1
745  23   3    750  62      1
746  39   1    250  39      1
747  72   1    250  72      1

[748 rows x 5 columns]

In [ ]:
df.head()

V1  V2     V3  V4  Class
0   2  50  12500  98      2
1   0  13   3250  28      2
2   1  16   4000  35      2
3   2  20   5000  45      2
4   1  24   6000  77      1

we have learned about Simple Linear Regression, where a single Independent/Predictor(X) variable is used to model the response variable (Y). But there may be various cases in which the response variable is affected by more than one predictor variable; for such cases, the Multiple Linear Regression algorithm is used.

Moreover, Multiple Linear Regression is an extension of Simple Linear regression as it takes more than one predictor variable to predict the response variable.

In [ ]:
import matplotlib.pyplot as mtp  
#Extracting Independent and dependent Variable  
x= df.iloc[:, :-1].values  
y= df.iloc[:, 4].values 

In [ ]:
print(x)

[[    2    50 12500    98]
 [    0    13  3250    28]
 [    1    16  4000    35]
 ...
 [   23     3   750    62]
 [   39     1   250    39]
 [   72     1   250    72]]


In [ ]:
print(y)

[2 2 2 2 1 1 2 1 2 2 1 1 2 1 2 2 2 2 2 2 2 1 2 2 1 1 1 2 2 1 1 2 2 2 1 2 2
 2 2 2 2 1 2 1 2 2 1 1 1 1 1 2 1 1 2 2 2 2 1 1 1 2 1 2 2 1 2 1 1 1 1 1 2 1
 2 2 2 1 1 1 2 1 1 1 2 1 1 1 1 2 2 1 1 1 1 1 1 2 2 2 2 2 1 1 1 1 1 1 1 1 2
 1 1 2 1 1 2 1 1 2 2 2 2 2 1 1 2 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1
 2 1 2 1 1 2 1 1 1 1 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 2 2 2 1 2 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 2 2 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 2
 2 1 2 2 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2 1 2 2 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1
 1 1 2 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 2 2 2 2 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 2 1 1 1 1 2 1 1 1 2
 2 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 2
 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 2 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [ ]:
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)  

In [ ]:
#Fitting the MLR model to the training set:  
from sklearn.linear_model import LinearRegression  
regressor= LinearRegression()  
regressor.fit(x_train, y_train) 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
#Predicting the Test set result;  
y_pred= regressor.predict(x_test)

In [ ]:
print('Train Score: ', regressor.score(x_train, y_train))  
print('Test Score: ', regressor.score(x_test, y_test))  

Train Score:  0.11825132216729128
Test Score:  0.1547468814759284


Here the accuracy received is very less so we need to apply various techniques to improve accuracy